//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccyr
    {
        public string ccyr_ccy_code { get; set; }
        public string ccyr_ccyt_type { get; set; }
        public Nullable<System.DateTime> ccyr_date_time { get; set; }
        public Nullable<double> ccyr_cost_rate { get; set; }
        public Nullable<float> ccyr_margin_adj { get; set; }
        public Nullable<double> ccyr_rate { get; set; }
        public Nullable<short> ccyr_cyclic_no { get; set; }
        public string ccyr_user_id { get; set; }
        public Nullable<System.DateTime> ccyr_amend_date { get; set; }
        public string ccyr_state { get; set; }
        public int unique_id { get; set; }
    }
}
