//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clnt
    {
        public string clnt_id { get; set; }
        public string clnt_short_name { get; set; }
        public string clnt_long_name { get; set; }
        public Nullable<short> clnt_cyclic_no { get; set; }
        public string clnt_user_id { get; set; }
        public Nullable<System.DateTime> clnt_amend_date { get; set; }
        public string clnt_state { get; set; }
        public int unique_id { get; set; }
    }
}
