//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cloc
    {
        public string cloc_clnt_id { get; set; }
        public string cloc_id { get; set; }
        public string cloc_name { get; set; }
        public string cloc_addr_1 { get; set; }
        public string cloc_addr_2 { get; set; }
        public string cloc_addr_3 { get; set; }
        public string cloc_postcode { get; set; }
        public string cloc_cnty_code { get; set; }
        public Nullable<double> cloc_limit { get; set; }
        public string cloc_email_addr { get; set; }
        public string cloc_phone_no { get; set; }
        public Nullable<short> cloc_cyclic_no { get; set; }
        public string cloc_user_id { get; set; }
        public Nullable<System.DateTime> cloc_amend_date { get; set; }
        public string cloc_state { get; set; }
        public string cloc_ttyp_type { get; set; }
        public int unique_id { get; set; }
    }
}
