//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnrd
    {
        public string cnrd_cnty_code { get; set; }
        public string cnrd_prod_id { get; set; }
        public string cnrd_ccy_code { get; set; }
        public Nullable<short> cnrd_sort_order { get; set; }
        public Nullable<short> cnrd_cyclic_no { get; set; }
        public string cnrd_user_id { get; set; }
        public Nullable<System.DateTime> cnrd_amend_date { get; set; }
        public string cnrd_state { get; set; }
        public int unique_id { get; set; }
    }
}
