//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnty
    {
        public string cnty_code { get; set; }
        public string cnty_name { get; set; }
        public Nullable<short> cnty_cyclic_no { get; set; }
        public string cnty_user_id { get; set; }
        public Nullable<System.DateTime> cnty_amend_date { get; set; }
        public string cnty_state { get; set; }
        public int unique_id { get; set; }
    }
}
