//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public string comments_table { get; set; }
        public string comments_index_1 { get; set; }
        public string comments_index_2 { get; set; }
        public string comments_notes { get; set; }
        public short comments_cyclic_no { get; set; }
        public string comments_user_id { get; set; }
        public System.DateTime comments_amend_date { get; set; }
        public string comments_state { get; set; }
        public int unique_id { get; set; }
    }
}
