//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comn
    {
        public string comn_prod_id { get; set; }
        public string comn_clnt_id { get; set; }
        public string comn_sub_prod { get; set; }
        public string comn_ttyp_type { get; set; }
        public string comn_settle_ccy { get; set; }
        public double comn_min_amt { get; set; }
        public double comn_max_amt { get; set; }
        public Nullable<double> comn_fixed { get; set; }
        public Nullable<double> comn_fee_per_item { get; set; }
        public Nullable<double> comn_rate { get; set; }
        public Nullable<short> comn_cyclic_no { get; set; }
        public string comn_user_id { get; set; }
        public Nullable<System.DateTime> comn_amend_date { get; set; }
        public string comn_state { get; set; }
        public int unique_id { get; set; }
    }
}
