//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp
    {
        public string comp_tran_comp_id { get; set; }
        public string comp_id_type { get; set; }
        public string comp_id_number { get; set; }
        public string comp_id_issue_place { get; set; }
        public Nullable<System.DateTime> comp_id_issue_date { get; set; }
        public string comp_spare_1 { get; set; }
        public string comp_spare_2 { get; set; }
        public Nullable<short> comp_cyclic_no { get; set; }
        public string comp_user_id { get; set; }
        public Nullable<System.DateTime> comp_amend_date { get; set; }
        public string comp_state { get; set; }
        public int unique_id { get; set; }
    }
}
