//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comt
    {
        public string comt_comn_prod_id { get; set; }
        public string comt_description { get; set; }
        public Nullable<short> comt_cyclic_no { get; set; }
        public string comt_user_id { get; set; }
        public Nullable<System.DateTime> comt_amend_date { get; set; }
        public string comt_state { get; set; }
        public int unique_id { get; set; }
    }
}
