//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deli
    {
        public string deli_comp_id { get; set; }
        public string deli_tran_id { get; set; }
        public Nullable<System.DateTime> deli_delv_date { get; set; }
        public string deli_name_1 { get; set; }
        public string deli_name_2 { get; set; }
        public string deli_company_name { get; set; }
        public string deli_dept_name { get; set; }
        public string deli_addr_1 { get; set; }
        public string deli_addr_2 { get; set; }
        public string deli_addr_3 { get; set; }
        public string deli_postcode { get; set; }
        public string deli_phone { get; set; }
        public string deli_instructions { get; set; }
        public string deli_comments { get; set; }
        public Nullable<int> deli_dlvy_code { get; set; }
        public string deli_user_def_1 { get; set; }
        public string deli_user_def_2 { get; set; }
        public Nullable<short> deli_cyclic_no { get; set; }
        public string deli_user_id { get; set; }
        public Nullable<System.DateTime> deli_amend_date { get; set; }
        public string deli_state { get; set; }
        public int unique_id { get; set; }
    }
}
