//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dlvy
    {
        public int dlvy_code { get; set; }
        public string dlvy_description { get; set; }
        public double dlvy_rate { get; set; }
        public string dlvy_ccy_code { get; set; }
        public byte dlvy_sort_order { get; set; }
        public Nullable<short> dlvy_cyclic_no { get; set; }
        public string dlvy_user_id { get; set; }
        public Nullable<System.DateTime> dlvy_amend_date { get; set; }
        public string dlvy_state { get; set; }
        public int unique_id { get; set; }
    }
}
