//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estl
    {
        public string estl_tran_comp_id { get; set; }
        public string estl_stlt_type { get; set; }
        public string estl_card_type { get; set; }
        public string estl_card_expiry { get; set; }
        public string estl_card_name { get; set; }
        public string estl_card_number { get; set; }
        public string estl_card_auth { get; set; }
        public string estl_card_start { get; set; }
        public string estl_issue_no { get; set; }
        public Nullable<double> estl_amount { get; set; }
        public string estl_ccy_code { get; set; }
        public string estl_user_def_1 { get; set; }
        public string estl_user_def_2 { get; set; }
        public Nullable<short> estl_cyclic_no { get; set; }
        public string estl_user_id { get; set; }
        public Nullable<System.DateTime> estl_amend_date { get; set; }
        public string estl_state { get; set; }
        public int unique_id { get; set; }
    }
}
