//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inst
    {
        public string inst_property { get; set; }
        public string inst_description { get; set; }
        public string inst_value { get; set; }
        public Nullable<byte> inst_sort_order { get; set; }
        public bool inst_encrypt { get; set; }
        public short inst_cyclic_no { get; set; }
        public string inst_user_id { get; set; }
        public System.DateTime inst_amend_date { get; set; }
        public string inst_state { get; set; }
        public int unique_id { get; set; }
    }
}
