//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phist
    {
        public int phist_id { get; set; }
        public int phist_usrs_unique_id { get; set; }
        public string phist_password { get; set; }
        public Nullable<System.DateTime> phist_amend_date { get; set; }
    }
}
