//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pref
    {
        public string pref_clnt_id { get; set; }
        public string pref_loyalty_name { get; set; }
        public string pref_email { get; set; }
        public string pref_home_www { get; set; }
        public string pref_main_back { get; set; }
        public string pref_main_fore { get; set; }
        public string pref_table_back { get; set; }
        public string pref_table_fore { get; set; }
        public string pref_check_blz { get; set; }
        public string pref_check_accntno { get; set; }
        public string pref_home_dlvy { get; set; }
        public short pref_cyclic_no { get; set; }
        public string pref_user_id { get; set; }
        public System.DateTime pref_amend_date { get; set; }
        public string pref_state { get; set; }
        public int unique_id { get; set; }
    }
}
