//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod
    {
        public string prod_id { get; set; }
        public string prod_sub_prod { get; set; }
        public string prod_ttyp_type { get; set; }
        public string prod_desc { get; set; }
        public Nullable<int> prod_min_order { get; set; }
        public Nullable<int> prod_max_order { get; set; }
        public Nullable<bool> prod_show_available { get; set; }
        public string prod_ccyt_type { get; set; }
        public Nullable<short> prod_cyclic_no { get; set; }
        public string prod_user_id { get; set; }
        public Nullable<System.DateTime> prod_amend_date { get; set; }
        public string prod_state { get; set; }
        public int unique_id { get; set; }
    }
}
