//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setl
    {
        public string setl_tran_comp_id { get; set; }
        public string setl_xref_id { get; set; }
        public string setl_type { get; set; }
        public string setl_clnt_id { get; set; }
        public string setl_cloc_id { get; set; }
        public string setl_appl_name1 { get; set; }
        public string setl_appl_name2 { get; set; }
        public string setl_appl_addr1 { get; set; }
        public string setl_appl_addr2 { get; set; }
        public string setl_appl_addr3 { get; set; }
        public string setl_email { get; set; }
        public string setl_appl_postcode { get; set; }
        public Nullable<double> setl_local_ccy_amount { get; set; }
        public Nullable<double> setl_comm_amount { get; set; }
        public Nullable<double> setl_tax_amount { get; set; }
        public string setl_ccy_code { get; set; }
        public Nullable<int> setl_delivery_code { get; set; }
        public Nullable<double> setl_delivery_amt { get; set; }
        public short setl_status { get; set; }
        public string setl_phone_no { get; set; }
        public string setl_work_phone { get; set; }
        public string setl_mobile_phone { get; set; }
        public string setl_dlvy_ref { get; set; }
        public Nullable<byte> setl_market_info { get; set; }
        public string setl_loyalty_no { get; set; }
        public string setl_user_def_1 { get; set; }
        public string setl_user_def_2 { get; set; }
        public short setl_cyclic_no { get; set; }
        public string setl_user_id { get; set; }
        public System.DateTime setl_amend_date { get; set; }
        public string setl_state { get; set; }
        public int unique_id { get; set; }
    }
}
