//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stlt
    {
        public string stlt_type { get; set; }
        public string stlt_code { get; set; }
        public string stlt_name { get; set; }
        public Nullable<short> stlt_cyclic_no { get; set; }
        public string stlt_user_id { get; set; }
        public Nullable<System.DateTime> stlt_amend_date { get; set; }
        public string stlt_state { get; set; }
        public int unique_id { get; set; }
    }
}
