//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public string taxs_prod_id { get; set; }
        public string taxs_sub_prod_id { get; set; }
        public short taxs_taxb_code { get; set; }
        public string taxs_ttyp_type { get; set; }
        public Nullable<double> taxs_rate { get; set; }
        public Nullable<short> taxs_cyclic_no { get; set; }
        public string taxs_user_id { get; set; }
        public Nullable<System.DateTime> taxs_amend_date { get; set; }
        public string taxs_state { get; set; }
        public int unique_id { get; set; }
    }
}
