//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tddt
    {
        public string tddt_tran_id { get; set; }
        public short tddt_row_no { get; set; }
        public Nullable<decimal> tddt_ccy_denm { get; set; }
        public Nullable<short> tddt_pack_size { get; set; }
        public Nullable<int> tddt_qty { get; set; }
        public string tddt_denm_class { get; set; }
        public string tddt_user_def_1 { get; set; }
        public string tddt_user_def_2 { get; set; }
        public Nullable<short> tddt_cyclic_no { get; set; }
        public string tddt_user_id { get; set; }
        public Nullable<System.DateTime> tddt_amend_date { get; set; }
        public string tddt_state { get; set; }
        public int unique_id { get; set; }
    }
}
