//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMOEntities : DbContext
    {
        public TMOEntities()
            : base("name=TMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ccy> ccies { get; set; }
        public virtual DbSet<ccyr> ccyrs { get; set; }
        public virtual DbSet<ccyt> ccyts { get; set; }
        public virtual DbSet<clnt> clnts { get; set; }
        public virtual DbSet<cloc> clocs { get; set; }
        public virtual DbSet<cnrd> cnrds { get; set; }
        public virtual DbSet<cnty> cnties { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<comn> comns { get; set; }
        public virtual DbSet<comp> comps { get; set; }
        public virtual DbSet<comt> comts { get; set; }
        public virtual DbSet<deli> delis { get; set; }
        public virtual DbSet<dlvy> dlvies { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<estl> estls { get; set; }
        public virtual DbSet<inst> insts { get; set; }
        public virtual DbSet<phist> phists { get; set; }
        public virtual DbSet<pref> prefs { get; set; }
        public virtual DbSet<prod> prods { get; set; }
        public virtual DbSet<setl> setls { get; set; }
        public virtual DbSet<stdn> stdns { get; set; }
        public virtual DbSet<stlt> stlts { get; set; }
        public virtual DbSet<taxb> taxbs { get; set; }
        public virtual DbSet<tax> taxs { get; set; }
        public virtual DbSet<tddt> tddts { get; set; }
        public virtual DbSet<tran> trans { get; set; }
        public virtual DbSet<ttyp> ttyps { get; set; }
        public virtual DbSet<usr> usrs { get; set; }
    }
}
