//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran
    {
        public string tran_id { get; set; }
        public string tran_comp_id { get; set; }
        public string tran_prod_id { get; set; }
        public string tran_sub_prod { get; set; }
        public string tran_ttyp_type { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_clnt_id { get; set; }
        public string tran_cloc_id { get; set; }
        public string tran_ccy_code { get; set; }
        public Nullable<double> tran_ccy1_amt { get; set; }
        public Nullable<double> tran_exch_rate { get; set; }
        public Nullable<double> tran_true_rate { get; set; }
        public Nullable<byte> tran_denm_mix { get; set; }
        public Nullable<bool> tran_tourist_related { get; set; }
        public string tran_user_def_1 { get; set; }
        public string tran_user_def_2 { get; set; }
        public short tran_cyclic_no { get; set; }
        public string tran_user_id { get; set; }
        public System.DateTime tran_amend_date { get; set; }
        public string tran_state { get; set; }
        public int unique_id { get; set; }
    }
}
