//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttyp
    {
        public string ttyp_type { get; set; }
        public string ttyp_description { get; set; }
        public Nullable<short> ttyp_cyclic_no { get; set; }
        public string ttyp_user_id { get; set; }
        public Nullable<System.DateTime> ttyp_amend_date { get; set; }
        public string ttyp_state { get; set; }
        public int unique_id { get; set; }
    }
}
