//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmoWebAPI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr
    {
        public string usrs_company { get; set; }
        public string usrs_login { get; set; }
        public string usrs_password { get; set; }
        public double usrs_level { get; set; }
        public Nullable<System.DateTime> usrs_pwd_changed_date { get; set; }
        public Nullable<short> usrs_pwd_attempts { get; set; }
        public string usrs_status { get; set; }
        public Nullable<short> usrs_cyclic_no { get; set; }
        public string usrs_user_id { get; set; }
        public Nullable<System.DateTime> usrs_amend_date { get; set; }
        public string usrs_state { get; set; }
        public int unique_id { get; set; }
    }
}
